(function() {var implementors = {};
implementors['ethcore_util'] = ["impl <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>","impl <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/std/time/struct.Instant.html' title='std::time::Instant'>Instant</a>","impl <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/std/time/duration/struct.Duration.html' title='std::time::duration::Duration'>Duration</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/std/time/struct.SystemTime.html' title='std::time::SystemTime'>SystemTime</a>","impl&lt;'a&gt; <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;&amp;'a <a class='primitive' href='https://doc.rust-lang.org/nightly/std/primitive.str.html'>str</a>&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/collections/string/struct.String.html' title='collections::string::String'>String</a>","impl <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;<a class='struct' href='ethcore_util/uint/struct.U512.html' title='ethcore_util::uint::U512'>U512</a>&gt; for <a class='struct' href='ethcore_util/uint/struct.U512.html' title='ethcore_util::uint::U512'>U512</a>","impl <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;<a class='struct' href='ethcore_util/uint/struct.U256.html' title='ethcore_util::uint::U256'>U256</a>&gt; for <a class='struct' href='ethcore_util/uint/struct.U256.html' title='ethcore_util::uint::U256'>U256</a>","impl <a class='trait' href='ethcore_util/standard/ops/trait.Add.html' title='ethcore_util::standard::ops::Add'>Add</a>&lt;<a class='struct' href='ethcore_util/uint/struct.U128.html' title='ethcore_util::uint::U128'>U128</a>&gt; for <a class='struct' href='ethcore_util/uint/struct.U128.html' title='ethcore_util::uint::U128'>U128</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
